### ISSUE TITLE
HerbariumBerryBush Compatibility

### ISSUE THREAD

**Issue by LeandroTheDev** [LeandroTheDev/level_up#14]
**The bug**
When I use the clip action this error shows up and I don't know what to do. ``GreenPig``

**Logs with enableExtendedLog**
```
17.5.2024 22:57:15 [Server Error] Exception: Object reference not set to an instance of an object.
at LevelUP.Shared.OverwriteDamageInteraction.DamageItemFinish(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount) in /home/admin/Documents/LevelUP/LevelUP/Shared/OverrideDamageInteraction.cs:line 489
at herbarium.HerbariumBerryBush.GiveClipping(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in D:\VSMods\Herbarium\Herbarium\src\Block\HerbariumBerryBush.cs:line 229
at herbarium.HerbariumBerryBush.OnBlockInteractStop(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in D:\VSMods\Herbarium\Herbarium\src\Block\HerbariumBerryBush.cs:line 199
at Vintagestory.Server.ServerSystemBlockSimulation.callOnUsingBlock(ServerPlayer player, Block block, BlockSelection blockSel, Single& secondsPassed, Boolean callStop) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 531
at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 515
at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 257
at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138
```

**Singleplayer/LAN/Multiplayer?**
Only dedicated server

**Comment by LeandroTheDev** [comment]
Fixed in 1.1.9
