### ISSUE TITLE
player crash

### ISSUE THREAD

**Issue by kasirii** [LeandroTheDev/level_up#21]
I don't know what the reason is, just at some point all players started crashing from the server with the same error.

18.7.2024 21:55:39 [Error] Exception: .NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider speci>
   at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueNotSupported()
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Double value)
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at LevelUP.Server.LevelVitality.SaveState() in E:\Templates\LevelUP\LevelUP\Server\LevelVitality.cs:line 54
   at Vintagestory.Server.ServerEventManager.TriggerGameWorldBeingSaved() in VintagestoryLib\Server\ServerEventManager.cs:line 540

multiplayer

**Comment by LeandroTheDev** [comment]
I need the full logs from server-main with enableExtendedLogs, i think theres is something wrong with the player health in your world, currently you can disable the vitality to temporary fix the problems

this crash happens when a player disconnects from the game correct?

**Comment by kasirii** [comment]
This happens when a player connects. there are no original logs from the moment it happened. i can only give you logs where the player tries to connect, gets an error and crashes.

**Comment by LeandroTheDev** [comment]
Did you added some 0 in any vitality configurations?

**Comment by LeandroTheDev** [comment]
this happens every new world?
if yes can you share me your configurations files?

**Comment by kasirii** [comment]
No, just the one we play on and only with one person. (the other player crashed for a different reason...). I have not changed the configuration files

**Comment by LeandroTheDev** [comment]
I'm going to try to do some treatments for this error to see if it resolves, this crashing player will probably have his life reset to default value

But as far as I know this was an isolated case, it could be something very specific, i believe that just a life reset treatment is enough to correct this problem in case of "infinity number"

**Comment by kasirii** [comment]
how can I reset the values for a player who can't log in?

**Comment by LeandroTheDev** [comment]
Disable the vitality in the configurations and try to login in

**Comment by kasirii** [comment]
Ok, we'll give it a try, thank you.

**Comment by LeandroTheDev** [comment]
Not tested but fixed in 1.2.4-pre.1
